//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatShop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CAT_SHOP1Entities1 : DbContext
    {
        public CAT_SHOP1Entities1()
            : base("name=CAT_SHOP1Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_Login> C_Login { get; set; }
        public virtual DbSet<BestCat> BestCats { get; set; }
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<CommentBlog> CommentBlogs { get; set; }
        public virtual DbSet<LastNew> LastNews { get; set; }
        public virtual DbSet<LoaiMeo> LoaiMeos { get; set; }
        public virtual DbSet<MaxMonneyCat> MaxMonneyCats { get; set; }
        public virtual DbSet<Meo> Meos { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<SellerCat> SellerCats { get; set; }
    }
}
